/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = number;
export type Id = string;
export type ErrorMessage = string;
export type CompactErrorMessage = string | null;
export type ExceptionType = string;
export type Device = string | string[] | null;

/**
 * Alarm message
 *
 * Args:
 *     severity (Alarms, Literal[0,1,2]): Severity level (0-2). ALARMS.WARNING = 0, ALARMS.MINOR = 1, ALARMS.MAJOR = 2
 *     info (ErrorInfo): Error information.
 *     metadata (dict, optional): Additional metadata.
 */
export interface AlarmMessage {
  metadata?: Metadata;
  severity: Severity;
  info: ErrorInfo;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface ErrorInfo {
  id?: Id;
  error_message: ErrorMessage;
  compact_error_message: CompactErrorMessage;
  exception_type: ExceptionType;
  device?: Device;
  [k: string]: unknown;
}
