/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Resource =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }[];

/**
 * Message for available resources such as scans, data processing plugins etc
 *
 * Args:
 *     resource (dict, list[dict]): Resource description
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface AvailableResourceMessage {
  metadata?: Metadata;
  resource: Resource;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
