/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Base Model class for BEC Messages
 *
 * Args:
 *     msg_type (str): ClassVar for the message type, subclasses should override this.
 *     metadata (dict, optional): Optional dictionary with metadata for the BECMessage
 */
export interface BECMessage {
  metadata?: Metadata;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
