/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Messages = unknown[];

/**
 * Message type to send a bundle of BECMessages.
 *
 * Used to bundle together various messages, i.e. used to emit data in the scan bundler.
 *
 * Args:
 *     messages (list): List of BECMessage objects that are bundled together
 *     metadata (dict, optional): Additional metadata to describe the scan
 *
 * Examples:
 *     >>> BundleMessage(messages=[ScanQueueMessage(...), ScanStatusMessage(...)], metadata = {...})
 */
export interface BundleMessage {
  metadata?: Metadata;
  messages?: Messages;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
