/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Message = string;
export type ShowAsap = boolean;
export type Rid = string | null;
export type Source =
  | "bec_ipython_client"
  | "scan_server"
  | "device_server"
  | "scan_bundler"
  | "file_writer"
  | "scihub"
  | "dap"
  | null;
export type Scope = string | null;
export type Severity = number;
/**
 * Time in seconds after which the message expires and should not be shown anymore. Defaults to 60 seconds. Set it to 0 to never expire the message.
 */
export type Expire = number;

/**
 * Message type for sending information to the client
 * Args:
 *     message (str): message to the client
 *     show_asap (bool, optional): True if the message should be shown immediately. Defaults to True
 *     # Note: The option show_asap = True/False is temporary disabled until a decision is made on how to handle it. TODO #286
 *     RID (str, optional): Request ID forwarded from the service, if available will be used to filter on the client site. Defaults to None.
 *     source (str, Literal[
 *         "bec_ipython_client",
 *         "scan_server",
 *         "device_server",
 *         "scan_bundler",
 *         "file_writer",
 *         "scihub",
 *         "dap",
 *         None]
 *         : Source of the message. Defaults to None.
 *     scope (str, optional): Scope of the message; Defaults to None. One can follow
 *                            a pattern to filter afterwards for specific client info; e.g. "scan", "rotation"
 *     severity (int, optional): severity level of the message (0: INFO, 1: WARNING, 2: ERROR); Defaults to 0
 *     expire (float, optional): Time in seconds after which the message expires and should not be shown anymore.
 *                               Defaults to 60 seconds. Set it to 0 to never expire the message.
 */
export interface ClientInfoMessage {
  metadata?: Metadata;
  message: Message;
  show_asap?: ShowAsap;
  RID?: Rid;
  source?: Source;
  scope?: Scope;
  severity?: Severity;
  expire?: Expire;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
