/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Message for DAP configuration
 *
 * Args:
 *     config (dict): DAP configuration dictionary
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface DAPConfigMessage {
  metadata?: Metadata;
  config: Config;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Config {
  [k: string]: unknown;
}
