/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Success = boolean;
export type Data = unknown[] | null;
export type Error = string | null;

/**
 * Message for DAP responses
 *
 * Args:
 *     success (bool): True if the request was successful
 *     data (tuple, optional): DAP data (tuple of data (dict) and metadata). Defaults to ({} , None).
 *     error (str, optional): DAP error. Defaults to None.
 *     dap_request (BECMessage, None): DAP request. Defaults to None.
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface DAPResponseMessage {
  metadata?: Metadata;
  success: Success;
  data?: Data;
  error?: Error;
  dap_request?: BECMessage | null;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
/**
 * Base Model class for BEC Messages
 *
 * Args:
 *     msg_type (str): ClassVar for the message type, subclasses should override this.
 *     metadata (dict, optional): Optional dictionary with metadata for the BECMessage
 */
export interface BECMessage {
  metadata?: Metadata1;
  [k: string]: unknown;
}
export interface Metadata1 {
  [k: string]: unknown;
}
