/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DapCls = string;
export type DapType = "continuous" | "on_demand";

/**
 * Message for DAP requests
 *
 * Args:
 *     dap_cls (str): DAP class name
 *     dap_type (Literal["continuous", "on_demand"]) : Different types of DAP modes
 *     config (dict): DAP configuration
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface DAPRequestMessage {
  metadata?: Metadata;
  dap_cls: DapCls;
  dap_type: DapType;
  config: Config;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Config {
  [k: string]: unknown;
}
