/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Device = string | string[] | null;
export type Status = "completed" | "running" | "error";
export type Id = string;
export type ErrorMessage = string;
export type CompactErrorMessage = string | null;
export type ExceptionType = string;
export type Device1 = string | string[] | null;
export type Device2 = string | string[] | null;
export type Action =
  | "rpc"
  | "set"
  | "read"
  | "kickoff"
  | "complete"
  | "trigger"
  | "stage"
  | "unstage"
  | "pre_scan"
  | "wait"
  | "scan_report_instruction"
  | "open_scan"
  | "baseline_reading"
  | "close_scan"
  | "open_scan_def"
  | "close_scan_def"
  | "publish_data_as_read"
  | "close_scan_group";
export type InstructionId = string;

export interface DeviceInstructionResponse {
  metadata?: Metadata;
  device: Device;
  status: Status;
  error_info?: ErrorInfo | null;
  instruction: DeviceInstructionMessage;
  instruction_id: InstructionId;
  result?: unknown;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface ErrorInfo {
  id?: Id;
  error_message: ErrorMessage;
  compact_error_message: CompactErrorMessage;
  exception_type: ExceptionType;
  device?: Device1;
  [k: string]: unknown;
}
/**
 * Message type for sending device instructions to the device server
 *
 * Args:
 *     device (str, list[str], None): Device name, list of device names or None
 *     action (Literal[ "rpc",
 *                     "set",
 *                     "read",
 *                     "kickoff",
 *                     "complete",
 *                     "trigger",
 *                     "stage",
 *                     "unstage",
 *                     "pre_scan",
 *                     "wait",
 *                     "scan_report_instruction",
 *                     "open_scan",
 *                     "baseline_reading",
 *                     "close_scan",
 *                     "open_scan_def",
 *                     "close_scan_def",
 *                     "publish_data_as_read",
 *                     "close_scan_group",
 *                     ]) : Device action, note rpc calls can run any method of the device. The function name needs to be specified in parameters['func']
 *     parameter (dict): Parameters required for the device action
 *     metadata (dict, optional): Metadata to describe the conditions of the device instruction
 *
 * Examples:
 *     >>> DeviceInstructionMessage(device="samx", action="stage", parameter={})
 */
export interface DeviceInstructionMessage {
  metadata?: Metadata1;
  device: Device2;
  action: Action;
  parameter: Parameter;
  [k: string]: unknown;
}
export interface Metadata1 {
  [k: string]: unknown;
}
export interface Parameter {
  [k: string]: unknown;
}
