/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Device = string;
export type Out =
  | string
  | {
      [k: string]: unknown;
    };
export type Success = boolean;

/**
 * Message type for sending device RPC return values from the device server
 *
 * Args:
 *     device (str): Device name.
 *     return_val (Any): Return value of the RPC call.
 *     out (str or dict): Output of the RPC call.
 *     success (bool, optional): True if the RPC call was successful. Defaults to True.
 *     metadata (dict, optional): Additional metadata.
 */
export interface DeviceRPCMessage {
  metadata?: Metadata;
  device: Device;
  return_val: ReturnVal;
  out: Out;
  success?: Success;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface ReturnVal {
  [k: string]: unknown;
}
