/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Device = string;
export type Success = boolean;
export type RequestId = string;

/**
 * Message type for sending device request status updates from the device server
 *
 * Args:
 *     device (str): Device name.
 *     success (bool): True if the request was successful.
 *     request_id (str): Request ID.
 *     metadata (dict, optional): Additional metadata.
 */
export interface DeviceReqStatusMessage {
  metadata?: Metadata;
  device: Device;
  success: Success;
  request_id: RequestId;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
