/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Data = string;
export type Device = string;
export type Timestamp = number;

/**
 * Message type for sending device monitor updates from the device server.
 *
 * The message is send from the device_server to monitor data coming from larger detector.
 *
 * Args:
 *     device (str): Device name.
 *     data (np.ndarray): Numpy array data from the monitor
 *     metadata (dict, optional): Additional metadata.
 */
export interface DeviceMonitor1DMessage {
  data: Data;
  metadata?: Metadata;
  device: Device;
  timestamp?: Timestamp;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
