/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Device = string;
export type Signal = string;
/**
 * Type of the ROI, e.g. 'rectangle', 'circle', 'polygon'
 */
export type RoiType = string;
export type Timestamp = number;

/**
 * Message type for sending device user ROI updates to and from the device server.
 *
 * Args:
 *     device (str): Device name.
 *     signal (str): Signal name associated with the ROI.
 *     roi_type (str): Type of the ROI, e.g., 'rectangle', 'circle', 'polygon'.
 *     roi (dict): Dictionary containing the ROI information, e.g., {"x": 100, "y": 200, "width": 50, "height": 50}.
 *     metadata (dict, optional): Additional metadata.
 */
export interface DeviceUserROIMessage {
  metadata?: Metadata;
  device: Device;
  signal: Signal;
  roi_type: RoiType;
  roi: Roi;
  timestamp?: Timestamp;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
/**
 * Dictionary containing the ROI information, e.g. {'x': 100, 'y': 200, 'width': 50, 'height': 50}
 */
export interface Roi {
  [k: string]: unknown;
}
