/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = "add" | "add_slice" | "replace";
export type MaxShape = (number | null)[] | null;
export type Index = number | null;

/**
 * Model for validating async update metadata sent with device data.
 *
 * The async update metadata controls how data is aggregated into datasets during a scan:
 * - add: Appends data to the existing dataset along the first axis
 * - add_slice: Appends a slice of data at a specific index (max 2D datasets)
 * - replace: Replaces the existing dataset (written after scan completion)
 *
 * Args:
 *     type (Literal["add", "add_slice", "replace"]): Type of async update operation
 *     max_shape (list[int | None], optional): Maximum shape of the dataset. Required for 'add' and 'add_slice' types.
 *                                              Use None for unlimited dimensions. E.g., [None] for 1D unlimited.
 *                                              None values must only appear at the beginning (e.g., [None, 1024] is valid, [1024, None] is not).
 *                                              When all dimensions are None, maximum is 2 dimensions (e.g., [None, None] is valid, [None, None, None] is not).
 *                                              For 'add_slice' type, max_shape cannot exceed two dimensions.
 *     index (int, optional): Row index for 'add_slice' operations. Required only for 'add_slice' type.
 *
 * Examples:
 *     >>> DeviceAsyncUpdate(type="add", max_shape=[None])
 *     >>> DeviceAsyncUpdate(type="add", max_shape=[None, 1024, 1024])
 *     >>> DeviceAsyncUpdate(type="add_slice", max_shape=[None, 1024], index=5)
 *     >>> DeviceAsyncUpdate(type="replace")
 */
export interface DeviceAsyncUpdate {
  type: Type;
  max_shape?: MaxShape;
  index?: Index;
  [k: string]: unknown;
}
