/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Data = string;
export type Device = string;
export type Signal = string;
export type Timestamp = number;

/**
 * Message type for sending device preview updates from the device server.
 * The message is sent from the device_server to monitor data streams, usually at
 * a reduced rate compared to the full data stream.
 *
 * Args:
 *     device (str): Device name.
 *     signal (str): Signal name, e.g. "image", "data", "preview".
 *     data (np.ndarray): Numpy array data from the preview.
 *     timestamp (float, optional): Timestamp of the message. Defaults to time.time().
 *     metadata (dict, optional): Additional metadata.
 */
export interface DevicePreviewMessage {
  data: Data;
  metadata?: Metadata;
  device: Device;
  signal: Signal;
  timestamp?: Timestamp;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
