/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Device = string;

/**
 * Message type for sending device info updates from the device server
 *
 * Args:
 *     device (str): Device name.
 *     info (dict): Device info as a dictionary.
 *     metadata (dict, optional): Additional metadata.
 */
export interface DeviceInfoMessage {
  metadata?: Metadata;
  device: Device;
  info: Info;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Info {
  [k: string]: unknown;
}
