/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action = ("add" | "set" | "update" | "reload" | "remove" | "reset" | "cancel") | null;
export type Config = {
  [k: string]: unknown;
} | null;

/**
 * Message type for sending device config updates
 *
 * Args:
 *     action (Literal['add', 'set', 'update', 'reload', 'reset', 'remove', 'cancel']) : Update of the device config.
 *     config (dict, or None): Device config (add, set, update) or None (reload, reset).
 *     metadata (dict, optional): Additional metadata.
 */
export interface DeviceConfigMessage {
  metadata?: Metadata;
  action?: Action;
  config?: Config;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
