/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Device = string;
export type Status = number;

/**
 * Message type for sending device status updates from the device server
 *
 * Args:
 *     device (str): Device name.
 *     status (int): Device status.
 *     metadata (dict, optional): Additional metadata.
 */
export interface DeviceStatusMessage {
  metadata?: Metadata;
  device: Device;
  status: Status;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
