/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Device = string;
export type Finished = boolean;
export type Success = boolean;
export type Index = number;
export type Total = number;

/**
 * Message type for sending device initialization progress updates
 *
 * Args:
 *     device (str): Device name.
 *     finished (bool): True if the initialization is finished.
 *     success (bool): True if the initialization was successful.
 *     index (int): Current progress index.
 *     total (int): Total number of steps for initialization.
 *     metadata (dict, optional): Additional metadata.
 */
export interface DeviceInitializationProgressMessage {
  metadata?: Metadata;
  device: Device;
  finished: Finished;
  success: Success;
  index: Index;
  total: Total;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
