/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Message type for sending device readings from the device server
 *
 * Args:
 *     signals (dict): Dictionary containing the device signals and their values
 *     metadata (dict, optional): Metadata to describe the conditions of the device reading
 *
 * Examples:
 *     >>> BECMessage.DeviceMessage(signals={'samx': {'value': 14.999033949016491, 'timestamp': 1686385306.0265112}, 'samx_setpoint': {'value': 15.0, 'timestamp': 1686385306.016806}, 'samx_motor_is_moving': {'value': 0, 'timestamp': 1686385306.026888}}}, metadata={'stream': 'primary', 'DIID': 353, 'RID': 'd3471acc-309d-43b7-8ff8-f986c3fdecf1', 'point_id': 49, 'scan_id': '8e234698-358e-402d-a272-73e168a72f66', 'queue_id': '7a232746-6c90-44f5-81f5-74ab0ea22d4a'})
 */
export interface DeviceMessage {
  metadata?: Metadata;
  signals: Signals;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Signals {
  [k: string]: {
    [k: string]: unknown;
  };
}
