/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Endpoint = string;

/**
 * Message for endpoint information
 *
 * Args:
 *     endpoint (str): Endpoint URL
 *     metadata (dict, optional): Additional metadata.
 */
export interface EndpointInfoMessage {
  metadata?: Metadata;
  endpoint: Endpoint;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
