/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FilePath = string;
export type Done = boolean;
export type Successful = boolean;
export type IsMasterFile = boolean;
export type DeviceName = string | string[] | null;
export type FileType = string;
export type HintedH5Entries = {
  [k: string]: string;
} | null;

/**
 * File message to inform about the status of a file writing operation
 *
 * Args:
 *     file_path (str): Path to the file.
 *     done (bool): True if the file writing operation is done.
 *     successful (bool): True if the file writing operation was successful.
 *     device_name (str): Name of the device. If is_master_file is True, device_name is optional.
 *     is_master_file (bool, optional): True if the file is a master file. Defaults to False.
 *     file_type (str, optional): Type of the file. Defaults to "h5".
 *     hinted_h5_entries (dict[str, str], optional): Dictionary with hinted h5 entries. Defaults to None.
 *                 This allows the file writer to automatically create external links within the master.h5 file
 *                 written by BEC under the entry for the specified device. The dictionary should contain the
 *                 sub-entries and to where these should link in the external h5 file (file_path).
 *                 Example for device_name='eiger', and dict('data' : '/entry/data/data'), the location
 *                 '/entry/collection/devices/eiger/data' within the master file will link to '/entry/data/data'
 *                 of the external file.
 *     metadata (dict, optional): Additional metadata. Defaults to None.
 */
export interface FileMessage {
  metadata?: Metadata;
  file_path: FilePath;
  done: Done;
  successful: Successful;
  is_master_file?: IsMasterFile;
  device_name?: DeviceName;
  file_type?: FileType;
  hinted_h5_entries?: HintedH5Entries;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
