/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FilePath = string;

/**
 * File content message to inform about the content of a file
 *
 * Args:
 *     file_path (str): Path to the file.
 *     data (str): Content of the file.
 *     scan_info (dict): Scan information.
 *     metadata (dict, optional): Status metadata. Defaults to None.
 */
export interface FileContentMessage {
  metadata?: Metadata;
  file_path: FilePath;
  data: Data;
  scan_info: ScanInfo;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Data {
  [k: string]: unknown;
}
export interface ScanInfo {
  [k: string]: unknown;
}
