/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SelectedDevice = string;

/**
 * Message for Auto Update configuration
 *
 * Args:
 *     selected_device (str): the selected device for plotting
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface GUIAutoUpdateConfigMessage {
  metadata?: Metadata;
  selected_device: SelectedDevice;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
