/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Message for GUI data, i.e. update for DAP processes or scans
 *
 * Args:
 *     data (dict): GUI data
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface GUIDataMessage {
  metadata?: Metadata;
  data: Data;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Data {
  [k: string]: unknown;
}
