/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action = string;

/**
 * Message for GUI instructions
 *
 * Args:
 *     action (str): Instruction to be executed by the GUI
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface GUIInstructionMessage {
  metadata?: Metadata;
  action: Action;
  parameter: Parameter;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Parameter {
  [k: string]: unknown;
}
