/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Message for GUI registry state. The dictionary contains the state of the GUI registry.
 *
 * Args:
 *     state (dict[str, dict[Literal["gui_id", "name", "widget_class", "config", "__rpc__", "container_proxy"], str | bool | dict | None]): GUI registry state
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface GUIRegistryStateMessage {
  metadata?: Metadata;
  state: State;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface State {
  [k: string]: {
    [k: string]:
      | string
      | boolean
      | {
          [k: string]: unknown;
        }
      | null;
  };
}
