/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Host = string;
export type Deployment = string;
export type AvailableAccounts = string[];
export type AtlasLogin = boolean;

/**
 * Message for public login information
 *
 * Args:
 *     host (str): Hostname
 *     deployment (str): Deployment id
 */
export interface LoginInfoMessage {
  metadata?: Metadata;
  host: Host;
  deployment: Deployment;
  available_accounts: AvailableAccounts;
  atlas_login: AtlasLogin;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
