/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LogType = "trace" | "debug" | "info" | "success" | "warning" | "error" | "critical" | "console_log";
export type LogMsg =
  | {
      [k: string]: unknown;
    }
  | string;

/**
 * Log message
 *
 * Args:
 *     log_type (Literal["trace", "debug", "info", "success", "warning", "error", "critical", "console_log"]) : Log type.
 *     log_msg (dict or str): Log message.
 *     metadata (dict, optional): Additional metadata.
 */
export interface LogMessage {
  metadata?: Metadata;
  log_type: LogType;
  log_msg: LogMsg;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
