/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UpdateType = "add" | "remove" | "reload" | "reload_all";
export type MacroName = string | null;
export type FilePath = string | null;

/**
 * Message for macro updates
 *
 * Args:
 */
export interface MacroUpdateMessage {
  metadata?: Metadata;
  update_type: UpdateType;
  macro_name?: MacroName;
  file_path?: FilePath;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
