/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Observer = {
  [k: string]: unknown;
}[];

/**
 * Message for observer updates
 *
 * Args:
 *     observer (list[dict]): List of observer descriptions (dictionaries).
 *     metadata (dict, optional): Additional metadata.
 */
export interface ObserverMessage {
  metadata?: Metadata;
  observer: Observer;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
