/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Queue = string | null;
export type ExecutionId = string | null;
export type AbortAll = boolean | null;

/**
 * Message type to request aborting a procedure or procedure queue
 *
 * One and only one of the args should be supplied.
 *     Args:
 *         queue (str | None): the procedure queue to abort
 *         execution_id (str | None): the procedure execution to abort
 *         abort_all (bool | None): abort all procedures if true
 */
export interface ProcedureAbortMessage {
  metadata?: Metadata;
  queue?: Queue;
  execution_id?: ExecutionId;
  abort_all?: AbortAll;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
