/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueueName = string;
export type QueueType = "execution" | "unhandled";

/**
 * Message type for notifying watchers of changes to queues, mainly meant for GUI to consume
 */
export interface ProcedureQNotifMessage {
  metadata?: Metadata;
  queue_name: QueueName;
  queue_type: QueueType;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
