/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type Queue = string;
/**
 * @minItems 2
 * @maxItems 2
 */
export type ArgsKwargs = [unknown, unknown];
export type ExecutionId = string;

/**
 * Message type for sending procedure execution instructions to the scheduler
 *
 * Sent by the  user to the procedure_request topic. It will be consumed by the scan server.
 *     Args:
 *         identifier (str): name of the procedure registered with the server
 *         queue (str): the procedure queue this execution belongs to
 *         args_kwargs (tuple[tuple[Any, ...], dict[str, Any]]): arguments for the procedure function
 */
export interface ProcedureExecutionMessage {
  metadata?: Metadata;
  identifier: Identifier;
  queue: Queue;
  args_kwargs?: ArgsKwargs;
  execution_id: ExecutionId;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
