/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WorkerQueue = string;
export type ProcedureWorkerStatus = 1 | 2 | 3 | 4 | 5;
export type CurrentExecutionId = string | null;

/**
 * Message type for sending procedure worker status updates
 *
 * Args:
 *     worker_queue (str): Worker queue ID
 *     status (str): Worker status
 *     current_execution_id (str | None): ID of the current job, only allowed for RUNNING
 */
export interface ProcedureWorkerStatusMessage {
  metadata?: Metadata;
  worker_queue: WorkerQueue;
  status: ProcedureWorkerStatus;
  current_execution_id?: CurrentExecutionId;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
