/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Data =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }[];

/**
 * Message for processed data
 *
 * Args:
 *     data (dict, list[dict]): Dictionary with processed data or list of dictionaries with processed data.
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface ProcessedDataMessage {
  metadata?: Metadata;
  data: Data;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
