/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecutionId = string;
export type Action = "Started" | "Aborted" | "Finished";
export type Error = string | null;

/**
 * Message type for notifying watchers of changes to procedure executions, mainly meant for status helper to consume
 */
export interface ProcedureStatusUpdate {
  metadata?: Metadata;
  execution_id: ExecutionId;
  action: Action;
  error?: Error;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
