/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Identifier = string;
export type ArgsKwargs = [unknown, unknown] | null;
export type Queue = string | null;
export type ExecutionId = string;

/**
 * Message type for sending procedure requests to the server
 *
 * Sent by the API server / user to the procedure_request topic. It will be consumed by the procedure manager.
 *     Args:
 *         identifier (str): name of the procedure registered with the server
 *         queue (str | none): a key for the procedure queue
 */
export interface ProcedureRequestMessage {
  metadata?: Metadata;
  identifier: Identifier;
  args_kwargs?: ArgsKwargs;
  queue?: Queue;
  execution_id?: ExecutionId;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
