/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Value = number;
export type MaxValue = number;
export type Done = boolean;

/**
 * Message for communicating the progress of a long running task
 *
 * Args:
 *     value (float): Current progress value
 *     max_value (float): Maximum progress value
 *     done (bool): True if the task is done
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface ProgressMessage {
  metadata?: Metadata;
  value: Value;
  max_value: MaxValue;
  done: Done;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
