/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Message for raw data that was not encoded as a BECMessage.
 * The data dictionary is simply the raw data loaded using json.loads
 *
 * Args:
 *     data (Any): Raw data
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface RawMessage {
  metadata?: Metadata;
  data: Data;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Data {
  [k: string]: unknown;
}
