/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ScanType = string;
export type Queue = string;
export type Rid = string;
export type ScanMotors = string[];
export type IsScan = boolean;
export type ScanNumber = number | null;
export type ScanId = string | null;
export type ReportInstructions =
  | {
      [k: string]: unknown;
    }[]
  | null;

/**
 * Model for a request block within a scan queue entry. It represents a single request in the scan queue, e.g. a single scan or rpc call.
 *
 * Args:
 *     msg (ScanQueueMessage): The original scan queue message containing the request details
 *     RID (str): Request ID associated with the request
 *     scan_motors (list[str]): List of motors involved in the scan
 *     readout_priority (dict[Literal["monitored", "baseline", "async", "continuous", "on_request"], list[str]]): Readout priority for the request
 *     is_scan (bool): True if the request is a scan, False if it is an rpc call
 *     scan_number (int | None): Scan number if applicable
 *     scan_id (str | None): Scan ID if applicable
 *     report_instructions (list[dict] | None): List of report instructions for the scan, if any
 */
export interface RequestBlock {
  msg: ScanQueueMessage;
  RID: Rid;
  scan_motors: ScanMotors;
  readout_priority: ReadoutPriority;
  is_scan: IsScan;
  scan_number: ScanNumber;
  scan_id: ScanId;
  report_instructions?: ReportInstructions;
  [k: string]: unknown;
}
/**
 * Message type for sending scan requests to the scan queue
 *
 * Sent by the API server / user to the scan_queue topic. It will be consumed by the scan server.
 *     Args:
 *         scan_type (str): one of the registered scan types; either rpc calls or scan types defined in the scan server
 *         parameter (dict): required parameters for the given scan_stype
 *         queue (str): either "primary" or "interception"
 *         metadata (dict, optional): additional metadata to describe the scan
 *     Examples:
 *         >>> ScanQueueMessage(scan_type="dscan", parameter={"motor1": "samx", "from_m1:": -5, "to_m1": 5, "steps_m1": 10, "motor2": "samy", "from_m2": -5, "to_m2": 5, "steps_m2": 10, "exp_time": 0.1})
 */
export interface ScanQueueMessage {
  metadata?: Metadata;
  scan_type: ScanType;
  parameter: Parameter;
  queue?: Queue;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Parameter {
  [k: string]: unknown;
}
export interface ReadoutPriority {
  [k: string]: string[];
}
