/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Accepted = boolean;
export type Message =
  | string
  | {
      [k: string]: unknown;
    }
  | null;

/**
 * Message type for sending back decisions on the acceptance of requests
 *
 * Args:
 *     accepted (bool): True if the request was accepted
 *     message (str, dict, optional): String or dictionary describing the decision, e.g. "Invalid request"
 *     metadata (dict, optional): Additional metadata, defaults to None.
 *
 * Examples:
 *     >>> RequestResponseMessage(accepted=True, message="Request accepted")
 */
export interface RequestResponseMessage {
  metadata?: Metadata;
  accepted: Accepted;
  message?: Message;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
