/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ScanId = string | null;
export type Status = "open" | "paused" | "aborted" | "halted" | "closed";
export type ScanNumber = number | null;
export type SessionId = string | null;
/**
 * Number of points in the scan. Only relevant if the number of points is determined by BEC.
 */
export type NumPoints = number | null;
/**
 * Name of the scan, e.g. 'line_scan'
 */
export type ScanName = string | null;
/**
 * Type of scan
 */
export type ScanType = ("step" | "fly") | null;
export type DatasetNumber = number | null;
export type ScanReportDevices = string[] | null;
export type UserMetadata = {
  [k: string]: unknown;
} | null;
export type ReadoutPriority = {
  [k: string]: string[];
} | null;
export type ScanParameters = {
  [k: string]: unknown;
} | null;
export type RequestInputs = {
  [k: string]: unknown;
} | null;
export type Timestamp = number;

/**
 * Message type for sending scan status updates.
 *
 * Args:
 *     scan_id (str): Unique scan ID
 *     status (Literal["open", "paused", "aborted", "halted", "closed"]) : Current scan status
 *     scan_number (int, optional): Scan number
 *     session_id (str, optional): Session ID
 *     num_points (int, optional): Number of points in the scan. Only relevant if the number of points is determined by BEC.
 *     scan_name (str, optional): Name of the scan, e.g. 'line_scan'
 *     scan_type (Literal["step", "fly"], optional): Type of scan
 *     dataset_number (int, optional): Dataset number
 *     scan_report_devices (list[str], optional): List of devices that are part of the scan report
 *     user_metadata (dict, optional): User metadata
 *     readout_priority (dict[Literal["monitored", "baseline", "async", "continuous", "on_request"], list[str]], optional): Readout priority
 *     scan_parameters (dict[Literal["exp_time", "frames_per_trigger", "settling_time", "readout_time"] | str, Any], optional): Scan parameters such as exposure time, frames per trigger, settling time, readout time
 *     request_inputs (dict[Literal["arg_bundle", "inputs", "kwargs"], Any], optional): Scan input
 *     info (dict): Dictionary containing additional information about the scan
 *     timestamp (float, optional): Timestamp of the message. Defaults to time.time()
 *
 * Examples:
 *     >>> ScanStatusMessage(scan_id="1234", status="open", info={"positions": {"samx": 0.5, "samy": 0.5}})
 */
export interface ScanStatusMessage {
  metadata?: Metadata;
  scan_id: ScanId;
  status: Status;
  scan_number?: ScanNumber;
  session_id?: SessionId;
  num_points?: NumPoints;
  scan_name?: ScanName;
  scan_type?: ScanType;
  dataset_number?: DatasetNumber;
  scan_report_devices?: ScanReportDevices;
  user_metadata?: UserMetadata;
  readout_priority?: ReadoutPriority;
  scan_parameters?: ScanParameters;
  request_inputs?: RequestInputs;
  info: Info;
  timestamp?: Timestamp;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Info {
  [k: string]: unknown;
}
