/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ScanId = string;
export type ScanNumber = number;
export type DatasetNumber = number;
export type FilePath = string;
export type ExitStatus = "closed" | "aborted" | "halted";
export type StartTime = number;
export type EndTime = number;
export type ScanName = string;
export type NumPoints = number;
export type RequestInputs = {
  [k: string]: unknown;
} | null;
export type StoredDataInfo = {
  [k: string]: {
    [k: string]: _StoredDataInfo;
  };
} | null;
export type Shape = number[];
export type Dtype = string | null;

/**
 * Message type for sending scan history data from the file writer
 *
 * Args:
 *     scan_id (str): Scan ID.
 *     scan_number (int): Scan number.
 *     dataset_number (int): Dataset number.
 *     file_path (str): Path to the file.
 *     exit_status (Literal["closed", "aborted", "halted"]): Exit status of the scan.
 *     start_time (float): Start time of the scan.
 *     end_time (float): End time of the scan.
 *     scan_name (str): Name of the scan.
 *     num_points (int): Number of points in the scan.
 *     request_inputs (dict, optional): Inputs for the scan request, if available.
 *     stored_data_info (dict[str, dict[str, _StoredDataInfo]], optional): Information about the stored data for each device in the scan.
 *     metadata (dict, optional): Additional metadata.
 */
export interface ScanHistoryMessage {
  metadata?: Metadata;
  scan_id: ScanId;
  scan_number: ScanNumber;
  dataset_number: DatasetNumber;
  file_path: FilePath;
  exit_status: ExitStatus;
  start_time: StartTime;
  end_time: EndTime;
  scan_name: ScanName;
  num_points: NumPoints;
  request_inputs?: RequestInputs;
  stored_data_info?: StoredDataInfo;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
/**
 * Internal class to store data info for each device in the scan history message
 *
 * Args:
 *     shape (tuple): Shape of the data for the device.
 *     dtype (str, optional): Data type of the data for the device. Defaults to None.
 */
export interface _StoredDataInfo {
  shape?: Shape;
  dtype?: Dtype;
  [k: string]: unknown;
}
