/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ScanId = string | string[] | null[] | null;
export type Action = "pause" | "deferred_pause" | "continue" | "abort" | "clear" | "restart" | "halt" | "resume";
export type Queue = string;

/**
 * Message type for sending scan queue modifications
 *
 * Args:
 *     scan_id (str): Unique scan ID
 *     action (str): One of the actions defined in ACTIONS: ("pause", "deferred_pause", "continue", "abort", "clear", "restart", "halt", "resume")
 *     parameter (dict): Additional parameters for the action
 *     queue (str): Defaults to "primary" queue. The name of the queue that receives the modification.
 *     metadata (dict, optional): Additional metadata to describe and identify the scan.
 *
 * Examples:
 *     >>> ScanQueueModificationMessage(scan_id=scan_id, action="abort", parameter={})
 */
export interface ScanQueueModificationMessage {
  metadata?: Metadata;
  scan_id: ScanId;
  action: Action;
  parameter: Parameter;
  queue?: Queue;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Parameter {
  [k: string]: unknown;
}
