/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ScanId = string;
export type Action = "move_up" | "move_down" | "move_top" | "move_bottom" | "move_to";
export type Queue = string;
export type TargetPosition = number | null;

/**
 * Message type for sending scan queue order modifications
 *
 * Args:
 *     scan_id (str): Unique scan ID
 *     action (str): One of the actions defined in ACTIONS: ("move_up", "move_down", "move_top", "move_bottom", "move_to")
 *     queue (str): Defaults to "primary" queue. The name of the queue that receives the modification.
 *     metadata (dict, optional): Additional metadata to describe and identify the scan.
 *
 * Examples:
 *     >>> ScanQueueOrderMessage(scan_id=scan_id, action="move_up")
 */
export interface ScanQueueOrderMessage {
  metadata?: Metadata;
  scan_id: ScanId;
  action: Action;
  queue?: Queue;
  target_position?: TargetPosition;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
