/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ScanType = string;
export type Queue = string;

/**
 * Message type for sending scan requests to the scan queue
 *
 * Sent by the API server / user to the scan_queue topic. It will be consumed by the scan server.
 *     Args:
 *         scan_type (str): one of the registered scan types; either rpc calls or scan types defined in the scan server
 *         parameter (dict): required parameters for the given scan_stype
 *         queue (str): either "primary" or "interception"
 *         metadata (dict, optional): additional metadata to describe the scan
 *     Examples:
 *         >>> ScanQueueMessage(scan_type="dscan", parameter={"motor1": "samx", "from_m1:": -5, "to_m1": 5, "steps_m1": 10, "motor2": "samy", "from_m2": -5, "to_m2": 5, "steps_m2": 10, "exp_time": 0.1})
 */
export interface ScanQueueMessage {
  metadata?: Metadata;
  scan_type: ScanType;
  parameter: Parameter;
  queue?: Queue;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Parameter {
  [k: string]: unknown;
}
