/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ScanId = string;

/**
 * Message type for sending scan baseline data from the scan bundler
 *
 * Args:
 *     scan_id (str): Scan ID.
 *     data (dict): Scan baseline data.
 *     metadata (dict, optional): Additional metadata.
 */
export interface ScanBaselineMessage {
  metadata?: Metadata;
  scan_id: ScanId;
  data: Data;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Data {
  [k: string]: unknown;
}
