/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ScriptId = string;
export type Status = "running" | "completed" | "failed" | "aborted";
export type CurrentLines = number[] | null;
export type Traceback = string | null;

/**
 * Message for script execution
 *
 * Args:
 *     script_id (str): Unique identifier for the script
 *     status (Literal["running", "completed", "failed", "aborted"]): Execution status
 *     current_lines (list[int], optional): Current line numbers being executed. Defaults to None.
 *     traceback (str, optional): Traceback information. Defaults to None.
 */
export interface ScriptExecutionInfoMessage {
  metadata?: Metadata;
  script_id: ScriptId;
  status: Status;
  current_lines?: CurrentLines;
  traceback?: Traceback;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
