/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;

/**
 * Message for service metrics
 *
 * Args:
 *     name (str): Name of the service.
 *     metrics (dict): Dictionary with service metrics.
 *     metadata (dict, optional): Additional metadata.
 */
export interface ServiceMetricMessage {
  metadata?: Metadata;
  name: Name;
  metrics: Metrics;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Metrics {
  [k: string]: unknown;
}
