/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Message for service responses
 *
 * Args:
 *     response (dict): Service response
 *     metadata (dict, optional): Metadata. Defaults to None.
 */
export interface ServiceResponseMessage {
  metadata?: Metadata;
  response: Response;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Response {
  [k: string]: unknown;
}
