/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
/**
 * BEC status enum
 */
export type BECStatus = 2 | 1 | 0 | -1;

/**
 * Status message
 *
 * Args:
 *     name (str): Name of the status.
 *     status (BECStatus): Value of the BECStatus enum (RUNNING = 2,  BUSY = 1, IDLE = 0, ERROR = -1).
 *     info (dict): Status info.
 *     metadata (dict, optional): Additional metadata.
 */
export interface StatusMessage {
  metadata?: Metadata;
  name: Name;
  status: BECStatus;
  info: Info;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Info {
  [k: string]: unknown;
}
