/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Message for ACL accounts
 *
 * Args:
 *     accounts (dict): ACL accounts
 */
export interface ACLAccountsMessage {
  metadata?: Metadata;
  accounts: Accounts;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Accounts {
  [k: string]: {
    [k: string]: string[] | string;
  };
}
