/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Message to inform about a global variable
 *
 * Args:
 *     value (Any): Variable value, can be of any type.
 *     metadata (dict, optional): Additional metadata.
 */
export interface VariableMessage {
  metadata?: Metadata;
  value: Value;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Value {
  [k: string]: unknown;
}
